- name: Config User local
  fortiosconfig:
    action: "set"
    host: "{{ host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vdom:  "{{ vdom }}"
    config: "user local"
    config_parameters:
      name: "{{ item.name }}"
      type: "{{ item.type }}"
      passwd: "{{ item.passwd }}"
      email-to: "{{ item.email_to }}"
      passwd-policy: "{{ item.passwd_policy }}"
      authtimeout: "{{ item.authtimeout }}"
  with_items: "{{ user }}"


